sonar.organization=mehdital
sonar.projectKey=mehdital_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
sonar.projectName=BobApp
sonar.sourceEncoding=UTF-8

# scanne le code back et front
sonar.sources=back/src/main,front/src
# Répertoires de tests
sonar.tests=back/src/test,front/src
# Fichiers de tests
sonar.test.inclusions=back/src/test/**/*.java,front/src/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/target/**,front/src/environments/**,front/src/test.ts,front/src/main.ts,.github/**,**/Dockerfile

# Back 
sonar.java.binaries=back/target/classes
# Rapports de tests
sonar.junit.reportPaths=back/target/surefire-reports
# Rapport JaCoCo (coverage back)
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml

# Front
# Rapport généré par Karma (coverage front)
sonar.javascript.lcov.reportPaths=front/coverage/**/lcov.info